// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/subscription.proto

package subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBookCategorySubscribedUserEmails request payload
type GetBookCategorySubscribedUserEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookCategory  string                 `protobuf:"bytes,1,opt,name=book_category,json=bookCategory,proto3" json:"book_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookCategorySubscribedUserEmailsRequest) Reset() {
	*x = GetBookCategorySubscribedUserEmailsRequest{}
	mi := &file_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookCategorySubscribedUserEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookCategorySubscribedUserEmailsRequest) ProtoMessage() {}

func (x *GetBookCategorySubscribedUserEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookCategorySubscribedUserEmailsRequest.ProtoReflect.Descriptor instead.
func (*GetBookCategorySubscribedUserEmailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookCategorySubscribedUserEmailsRequest) GetBookCategory() string {
	if x != nil {
		return x.BookCategory
	}
	return ""
}

// GetBookCategorySubscribedUserEmails response payload
type GetBookCategorySubscribedUserEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookCategorySubscribedUserEmailsResponse) Reset() {
	*x = GetBookCategorySubscribedUserEmailsResponse{}
	mi := &file_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookCategorySubscribedUserEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookCategorySubscribedUserEmailsResponse) ProtoMessage() {}

func (x *GetBookCategorySubscribedUserEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookCategorySubscribedUserEmailsResponse.ProtoReflect.Descriptor instead.
func (*GetBookCategorySubscribedUserEmailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookCategorySubscribedUserEmailsResponse) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

var File_proto_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"\x18proto/subscription.proto\x12\fsubscription\"Q\n" +
	"*GetBookCategorySubscribedUserEmailsRequest\x12#\n" +
	"\rbook_category\x18\x01 \x01(\tR\fbookCategory\"E\n" +
	"+GetBookCategorySubscribedUserEmailsResponse\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails2\xb2\x01\n" +
	"\x13SubscriptionService\x12\x9a\x01\n" +
	"#GetBookCategorySubscribedUserEmails\x128.subscription.GetBookCategorySubscribedUserEmailsRequest\x1a9.subscription.GetBookCategorySubscribedUserEmailsResponseB*Z(transport/grpc/microservice/subscriptionb\x06proto3"

var (
	file_proto_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_proto_rawDescData []byte
)

func file_proto_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_proto_rawDesc), len(file_proto_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_proto_rawDescData
}

var file_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_subscription_proto_goTypes = []any{
	(*GetBookCategorySubscribedUserEmailsRequest)(nil),  // 0: subscription.GetBookCategorySubscribedUserEmailsRequest
	(*GetBookCategorySubscribedUserEmailsResponse)(nil), // 1: subscription.GetBookCategorySubscribedUserEmailsResponse
}
var file_proto_subscription_proto_depIdxs = []int32{
	0, // 0: subscription.SubscriptionService.GetBookCategorySubscribedUserEmails:input_type -> subscription.GetBookCategorySubscribedUserEmailsRequest
	1, // 1: subscription.SubscriptionService.GetBookCategorySubscribedUserEmails:output_type -> subscription.GetBookCategorySubscribedUserEmailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_subscription_proto_init() }
func file_proto_subscription_proto_init() {
	if File_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_proto_rawDesc), len(file_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_proto = out.File
	file_proto_subscription_proto_goTypes = nil
	file_proto_subscription_proto_depIdxs = nil
}
