// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookCategoryExists request payload
type BookCategoryExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookCategory  string                 `protobuf:"bytes,1,opt,name=book_category,json=bookCategory,proto3" json:"book_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookCategoryExistsRequest) Reset() {
	*x = BookCategoryExistsRequest{}
	mi := &file_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookCategoryExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCategoryExistsRequest) ProtoMessage() {}

func (x *BookCategoryExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCategoryExistsRequest.ProtoReflect.Descriptor instead.
func (*BookCategoryExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *BookCategoryExistsRequest) GetBookCategory() string {
	if x != nil {
		return x.BookCategory
	}
	return ""
}

// BookCategoryExists response payload
type BookCategoryExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookCategoryExistsResponse) Reset() {
	*x = BookCategoryExistsResponse{}
	mi := &file_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookCategoryExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCategoryExistsResponse) ProtoMessage() {}

func (x *BookCategoryExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCategoryExistsResponse.ProtoReflect.Descriptor instead.
func (*BookCategoryExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *BookCategoryExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x13proto/catalog.proto\x12\acatalog\"@\n" +
	"\x19BookCategoryExistsRequest\x12#\n" +
	"\rbook_category\x18\x01 \x01(\tR\fbookCategory\"4\n" +
	"\x1aBookCategoryExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2o\n" +
	"\x0eCatalogService\x12]\n" +
	"\x12BookCategoryExists\x12\".catalog.BookCategoryExistsRequest\x1a#.catalog.BookCategoryExistsResponseB%Z#transport/grpc/microservice/catalogb\x06proto3"

var (
	file_proto_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_proto_rawDescData []byte
)

func file_proto_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_proto_rawDescData
}

var file_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_catalog_proto_goTypes = []any{
	(*BookCategoryExistsRequest)(nil),  // 0: catalog.BookCategoryExistsRequest
	(*BookCategoryExistsResponse)(nil), // 1: catalog.BookCategoryExistsResponse
}
var file_proto_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.CatalogService.BookCategoryExists:input_type -> catalog.BookCategoryExistsRequest
	1, // 1: catalog.CatalogService.BookCategoryExists:output_type -> catalog.BookCategoryExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_catalog_proto_init() }
func file_proto_catalog_proto_init() {
	if File_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_proto = out.File
	file_proto_catalog_proto_goTypes = nil
	file_proto_catalog_proto_depIdxs = nil
}
